### ISSUE TITLE
No deserializer class for JSON

### ISSUE THREAD

**Issue by jvstein** [linkedin/python-avro-json-serializer#5]
I wasn't able to find a python class to turn the JSON provided by this library (and the Java [JsonDecoder](https://avro.apache.org/docs/1.8.2/api/java/org/apache/avro/io/JsonDecoder.html) class) into plain old python objects and dictionaries.

Would such a contribution be welcomed?

**Comment by sixninetynine** [comment]
@jvstein absolutely!

**Comment by jvstein** [comment]
@sixninetynine I submitted PR #6. It would be great to get some feedback when you have the time.

**Comment by sixninetynine** [comment]
merged & published on pypi @ 1.0.1

thanks again!
